# Generated by Django 4.2.6 on 2023-10-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='customer_id',
            new_name='Blog_id',
        ),
    ]
