# Generated by Django 4.2.6 on 2023-10-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_customer_id_blogpost_blog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='Blog_id',
            new_name='blog_id',
        ),
    ]
